### ISSUE TITLE
Reduce allocations during WeakWriteLockingHashConsingMap::get

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/vallang#130]
The special class `io.usethesource.vallang.util.WeakWriteLockingHashConsingMap$LookupWrapper` is constructed a lot.

Running java flight recorder it's the top allocation by far when running a rascal compiler. It also shows up in quite some places in the trace.

**Comment by DavyLandman** [comment]
This is about soft reference equals, not about ivalue equals.

I checked caffeine, they are doing something similar.

**Comment by jurgenvinju** [comment]
Let's not then. We're already depending on caffeine so that's alright. Which configuration of caffeine caches are we thinking about?

**Comment by DavyLandman** [comment]
Well the thing is, if you make a custom map implementation, you can inline the unwrapping of the weak reference, and call equals between the right unwrapped object. 

But this map might be replaced by a caffeine LoadingCache with weak reference keys, but I would have to check if it still only does referential equality. And if it guarantees atomic loader action.

**Comment by ben-manes** [comment]
It looks like your `HashConsingMap` is more commonly referred to as an `Interner` (ala `String.intern(s)`). Guava's `Interners.weak()` delegates to `MapMaker.weakKeys()` with a dummy value (your `WeakReference` value is not needed).

You depend on the object identity rather than equality throughout the runtime? That does make it harder if you cannot safely discard and recreate an equivalent object, and have the system work correctly. If you cannot use an off-the-shelf class like Guava's, then a quick fallback might be a two-level cache. A standard size-based to capture recency and frequency, and evict/load through a victim cache to maintain identity. That might absorb enough allocations of the lookup wrappers that the remainder fall within tolerance of the young gen collector.

**Comment by DavyLandman** [comment]
> Typically instead of a periodic poll one would use `ReferenceQueue#remove()` to block the thread on, e.g. see `java.lang.ref.Cleaner`. To avoid this thread, Caffeine and Guava check periodically as part of their maintenance routines which are guarded by a tryLock, so like `WeakHashMap` it is cleaned up in response to activity on the map.

True, I didn't want to puth the cleanup in the `get` logic, and also didn't want to create a thread per instance. But I'll reconsider moving it to the get logic.

> 
> I don't think you need to worry about demotion and can use an inclusive second-level cache. If we can assume that the reads from the weak cache are rarer due to the strong cache then the synchronization cost is negligible if simplified to a `WeakHashMap`. What do you think about something like below?
> 
> ```java
> private final Cache<E, E> strong = Caffeine.newBuilder().maximumSize(10_000).build();
> private final Map<E, WeakReference<E>> weak = Collections.synchronizedMap(new WeakHashMap<>());
> 
> public E get(E e) {
>   return strong.get(e, obj -> {
>     var interned = weak.get(obj);
>     E value = (interned == null) ? null : interned.get();
>     if (value == null) {
>       weak.put(obj, new WeakReference<>(obj));
>       value = obj;
>     }
>     return value;
>   });
> }
> ```

Interesting idea, so it's always in the weak cache, and gets promoted to the strong cache on a get? interesting.

**Comment by jurgenvinju** [comment]
Great discussion! Thanks for this.

Some thoughts:

* it is 100% likely that most types will be "build" several times during a normal run of a Rascal program and thus in a weak->strong cache nesting they would all end up in the strong cache pretty quickly; 
* For every version of the Rascal program as it is compiled/interpreted types of the previous version will become `dead` but they are already in the strong cache for the previous reason;
* The number of dead types is expectedly very small; only long runs of an IDE with many different versions of types lead to memory issues.
* So a clean up cycle of the cache is not something we'd need to spent time on every minute or every second. Rather once in an hour or so would be good enough IMHO. Consider that every unique type has to be typed in by someone, literally, during this process.
* In a normal run of a deployed Rascal program, all types are known and declared priori (at class-load time) and they never die. It is not reasonable to pay a lot of efficiency in this deployed context, because of the other development context.

**Comment by DavyLandman** [comment]
> > I don't think you need to worry about demotion ( @ben-manes)
> 
> Probably I read this wrong. This does not mean there will not be any demotion from the strong cache to the weak, but that it would not take up too much time to demote older references?
> 
> How would demotion work? We expect most types to go into the second level almost immediately, so I am worried about the demotion :-)

In @ben-manes approach, demotion works by the strong cache dropping entries after the 10_000 entries are reached. In that proposed configuration, the oldest entries are dropped (but that can be changed). Since the weak map contains all entries, you can always get the reference back from there (and thus promote them back).

I like the simplicity, but it does mean that you can get a very lock intensive startup phase where they are all putting stuff in the weak cache everytime. 

Based on these discussions I will update my branch a bit, make it a bit more simpler.

**Comment by ben-manes** [comment]
The reason why I didn't bother with demotion is because the strong cache's reference keeps the entry from being garbage collectable. Therefore we could avoid shuffling it back to the weak cache on eviction and as that work doesn't seem to offer any benefits.

You might consider pulling the custom hashmap code in from [Spring](https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/util/ConcurrentReferenceHashMap.java) (apache) or [Hibernate](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/internal/util/collections/ConcurrentReferenceHashMap.java) (LGPL). They are self contained and could be copied in directly to avoid the dependency. Neither depend on a background thread and support weak references without allocating on read.

**Comment by DavyLandman** [comment]
Thanks to this discussion, I've simplified the logic in the pull request (#131). it's ready for review now.
